#!/bin/sh
set -e

# Automatically added by dh_installsystemd/13.3.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.3.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'guest-vm-sync-time-rtc.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'guest-vm-sync-time-rtc.service' >/dev/null || true
		deb-systemd-helper unmask 'guest-vm-sync-time-rtc.service' >/dev/null || true
	fi
fi
# End automatically added section
