#!/bin/sh
set -e

# Automatically added by dh_installsystemd/13.3.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'guest-vm-sync-time-with-rtc.service' >/dev/null || true
fi
# End automatically added section
